apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - servicemonitor-backend.yaml
  - servicemonitor-mongodb.yaml
  - mongodb-exporter.yaml
  - jaeger.yaml
  - alerting-rules.yaml
  - dashboard-backend.yaml
  - dashboard-frontend.yaml
  - dashboard-mongodb.yaml
