apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: monitoring
  labels:
    app: backend
spec:
  namespaceSelector:
    matchNames:
      - debox
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
