apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: debox
  labels:
    app: frontend
    team: debox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        team: debox
    spec:
      containers:
        - name: frontend
          image: localhost:5443/debox/frontend:latest
          ports:
            - containerPort: 5173
          envFrom:
            - configMapRef:
                name: frontend-config
            - secretRef:
                name: frontend-secrets
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 15
            periodSeconds: 20
