apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: debox
  labels:
    app: frontend
    team: debox
spec:
  type: NodePort
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30080
  selector:
    app: frontend
