apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: debox-mongo
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: debox
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jpedrosa94/DeBOX.git
    targetRevision: main
    path: k8s/mongo
  destination:
    server: https://kubernetes.default.svc
    namespace: debox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
